// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Requirements',
      items: [{type: 'autogenerated', dirName: 'requirements'}],
    },
    {
      type: 'category',
      label: 'Research',
      items: [{type: 'autogenerated', dirName: 'research'}],
    },
    {
      type: 'category',
      label: 'UI Design',
      items: [{type: 'autogenerated', dirName: 'ui-design'}],
    },
    {
      type: 'category',
      label: 'System Design',
      items: [{type: 'autogenerated', dirName: 'system-design'}],
    },
    {
      type: 'category',
      label: 'Implementation',
      items: [{type: 'autogenerated', dirName: 'implementation'}],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [{type: 'autogenerated', dirName: 'testing'}],
    },
    {
      type: 'category',
      label: 'Evaluation',
      items: [{type: 'autogenerated', dirName: 'evaluation'}],
    },
    {
      type: 'category',
      label: 'Conclusion',
      items: [{type: 'autogenerated', dirName: 'conclusion'}],
    },
    {
      type: 'category',
      label: 'Appendices',
      items: [{type: 'autogenerated', dirName: 'appendices'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
